name: flux_query
description: "🚀 A lightweight and flexible data fetching and caching library for Flutter, inspired by React Query. Features stale-while-revalidate pattern, optimistic updates, and reactive UI."
version: 0.0.1
homepage: "https://github.com/interdev7/flux_query"
repository: "https://github.com/interdev7/flux_query"
documentation: "https://github.com/interdev7/flux_query/blob/main/README.md"
issue_tracker: "https://github.com/interdev7/flux_query/issues"

funding:
  - https://ko-fi.com/interdev7

keywords:
  - cache
  - query
  - data-fetching
  - react-query
  - flutter
  - stale-while-revalidate
  - optimistic-updates

topics:
  - data-fetching
  - caching
  - flutter

screenshots:
  - description: 'Flux Query DevTools showing cache status'
    path: screenshots/logo.png

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: false

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
